from enum import Enum

class PhysicsDomain(str, Enum):
    MECHANICS = "MECHANICS"
    FLUID_DYNAMICS = "FLUID_DYNAMICS"
    AERODYNAMICS = "AERODYNAMICS"
    THERMODYNAMICS = "THERMODYNAMICS"
    HEAT_TRANSFER = "HEAT_TRANSFER"
    ELECTROMAGNETICS = "ELECTROMAGNETICS"
    CONTROL_SYSTEMS = "CONTROL_SYSTEMS"
    STRUCTURAL_MECHANICS = "STRUCTURAL_MECHANICS"
    VIBRATIONS = "VIBRATIONS"
    ORBITAL_MECHANICS = "ORBITAL_MECHANICS"

class SolveStatus(str, Enum):
    EXACT = "EXACT"
    NUMERICAL = "NUMERICAL"
    APPROXIMATE = "APPROXIMATE"
    UNDERDETERMINED = "UNDERDETERMINED"
    INCONSISTENT = "INCONSISTENT"
    TIMEOUT = "TIMEOUT"
