from enum import Enum

class Role(str, Enum):
    CHIEF_ENGINEER = "CHIEF_ENGINEER"
    MECHANICAL_ENGINEER = "MECHANICAL_ENGINEER"
    ELECTRONICS_ENGINEER = "ELECTRONICS_ENGINEER"
    FIRMWARE_ENGINEER = "FIRMWARE_ENGINEER"
    SIMULATION_ENGINEER = "SIMULATION_ENGINEER"
    MANUFACTURING_ENGINEER = "MANUFACTURING_ENGINEER"
    COMPLIANCE_ENGINEER = "COMPLIANCE_ENGINEER"
    PROGRAM_MANAGER = "PROGRAM_MANAGER"
    VIEWER = "VIEWER"

class ReviewStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REQUIRES_CHANGES = "REQUIRES_CHANGES"

class Permission(str, Enum):
    READ = "READ"
    WRITE = "WRITE"
    REVIEW = "REVIEW"
    APPROVE = "APPROVE"
    ADMIN = "ADMIN"

class NotificationType(str, Enum):
    REVIEW_REQUESTED = "REVIEW_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    COMMENT_ADDED = "COMMENT_ADDED"
    MENTION = "MENTION"
    DEADLINE_APPROACHING = "DEADLINE_APPROACHING"
