from pathlib import Path
from typing import Dict
from simulation_execution.solvers.base_solver import BaseSolverAdapter, SolverError
from simulation_execution.schemas.simulation_models import SimulationJob, SimulationResult
from simulation_execution.schemas.enums import JobStatus
import re
import numpy as np

class CalculiXAdapter(BaseSolverAdapter):
    """Adapter for CalculiX structural solver (ccx)."""
    solver_name = "CalculiX"
    executable = "ccx"
    
    def prepare_input(self, job: SimulationJob) -> Path:
        work_dir = self.working_base / f"ccx_{job.id}"
        work_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate .inp file (CalculiX input format)
        inp_content = self._generate_inp(job)
        (work_dir / "model.inp").write_text(inp_content)
        return work_dir
        
    def _generate_inp(self, job: SimulationJob) -> str:
        """Generate a minimal CalculiX .inp file. In production, this would use
        a proper FEA preprocessor like Gmsh or generate from CAD."""
        lines = ["*HEADING", f"Auto-generated by Engineering OS - Job {job.id}"]
        
        # Materials
        for mat in job.materials:
            lines.append(f"*MATERIAL, NAME={mat.name}")
            lines.append(f"*ELASTIC")
            lines.append(f"{mat.youngs_modulus_pa}, {mat.poisson_ratio}")
            lines.append(f"*DENSITY")
            lines.append(f"{mat.density_kg_m3}")
            
        # Nodes (placeholder - in production, from mesh generator)
        lines.append("*NODE, NSET=ALL_NODES")
        lines.append("1, 0.0, 0.0, 0.0")
        lines.append("2, 1.0, 0.0, 0.0")
        
        # Elements (placeholder)
        lines.append("*ELEMENT, TYPE=C3D8, ELSET=ALL_ELEMS")
        lines.append("1, 1, 2, 2, 2, 2, 2, 2, 2")
        
        # Boundary conditions
        for bc in job.boundary_conditions:
            if bc.bc_type == "FIXED":
                lines.append("*BOUNDARY")
                lines.append(f"{bc.region}, 1, 3, 0.0")
            elif bc.bc_type == "FORCE":
                lines.append("*CLOAD")
                force = bc.values.get("force_n", 0)
                lines.append(f"{bc.region}, 2, {force}")
                
        lines.append("*STEP")
        lines.append("*STATIC")
        lines.append("*END STEP")
        
        return "\n".join(lines)
        
    def execute(self, work_dir: Path, config: Dict) -> Dict:
        cmd = [self.executable, "-i", "model", "-o", "model"]
        if config.get("cores", 1) > 1:
            cmd.extend(["-c", str(config["cores"])])
        return self._run_subprocess(cmd, work_dir, config.get("timeout_seconds", 3600))
        
    def parse_results(self, work_dir: Path) -> SimulationResult:
        """Parse .dat and .frd files for results."""
        dat_file = work_dir / "model.dat"
        frd_file = work_dir / "model.frd"
        
        max_stress = 0.0
        max_disp = 0.0
        convergence = []
        
        if dat_file.exists():
            content = dat_file.read_text()
            # Parse stress output
            stress_matches = re.findall(r"STRESS\s+([\d.E+-]+)", content)
            if stress_matches:
                max_stress = max(float(s) for s in stress_matches)
            # Parse displacement
            disp_matches = re.findall(r"DISP\s+([\d.E+-]+)", content)
            if disp_matches:
                max_disp = max(abs(float(d)) for d in disp_matches)
            # Parse convergence
            conv_matches = re.findall(r"SUMMARY.*?(\d+\.\d+)", content, re.DOTALL)
            convergence = [float(c) for c in conv_matches]
            
        return SimulationResult(
            job_id="",
            status=JobStatus.COMPLETED,
            max_stress_pa=max_stress,
            max_displacement_m=max_disp,
            convergence_data=convergence,
            result_files=[str(f) for f in work_dir.glob("*")]
        )
