"""
Troy — Document Generation Service
Generates structured engineering reports in Markdown/HTML format.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.documents.schemas import (
    DocumentGenerateRequest,
    DocumentResponse,
    DocumentListResponse,
)
from app.core.logging import get_logger

logger = get_logger("documents")


async def generate_document(
    data: DocumentGenerateRequest, db: AsyncSession
) -> DocumentResponse:
    """Generate an engineering document."""
    doc_id = str(uuid.uuid4())
    now = datetime.utcnow().isoformat()

    content = ""
    title = data.title

    if data.doc_type == "calculation_report" and data.calculation_id:
        content = await _generate_calculation_report(data.calculation_id, db)
        if not title:
            title = "Calculation Report"

    elif data.doc_type == "project_summary":
        content = await _generate_project_summary(data.project_id, db)
        if not title:
            title = "Project Summary"

    else:
        content = "# Custom Document\n\nGenerated by Troy Engineering Copilot.\n"
        if not title:
            title = "Custom Document"

    # Persist document
    await db.execute(
        text("""
            INSERT INTO documents (id, project_id, calculation_id, title, doc_type, format, content, created_at)
            VALUES (:id, :pid, :cid, :title, :type, :fmt, :content, :now)
        """),
        {
            "id": doc_id, "pid": data.project_id, "cid": data.calculation_id,
            "title": title, "type": data.doc_type, "fmt": data.format,
            "content": content, "now": now,
        },
    )
    await db.commit()

    return DocumentResponse(
        id=doc_id, project_id=data.project_id,
        calculation_id=data.calculation_id,
        title=title, doc_type=data.doc_type,
        format=data.format, content=content, created_at=now,
    )


async def list_project_documents(
    project_id: str, db: AsyncSession
) -> DocumentListResponse:
    """List all documents for a project."""
    result = await db.execute(
        text("""
            SELECT id, project_id, calculation_id, title, doc_type, format, content, created_at
            FROM documents WHERE project_id = :pid ORDER BY created_at DESC
        """),
        {"pid": project_id},
    )
    rows = result.fetchall()
    docs = [
        DocumentResponse(
            id=row[0], project_id=row[1], calculation_id=row[2],
            title=row[3], doc_type=row[4], format=row[5],
            content=row[6], created_at=row[7] or "",
        )
        for row in rows
    ]
    return DocumentListResponse(documents=docs, total=len(docs))


async def get_document(doc_id: str, db: AsyncSession) -> DocumentResponse | None:
    """Get a single document."""
    result = await db.execute(
        text("SELECT id, project_id, calculation_id, title, doc_type, format, content, created_at FROM documents WHERE id = :id"),
        {"id": doc_id},
    )
    row = result.fetchone()
    if not row:
        return None
    return DocumentResponse(
        id=row[0], project_id=row[1], calculation_id=row[2],
        title=row[3], doc_type=row[4], format=row[5],
        content=row[6], created_at=row[7] or "",
    )


# ── Report Generators ────────────────────────────────────────────
async def _generate_calculation_report(calc_id: str, db: AsyncSession) -> str:
    """Generate a Markdown report for a calculation."""
    # Fetch calculation
    result = await db.execute(
        text("SELECT title, formula_id, domain, inputs_json, outputs_json, execution_time_ms FROM calculations WHERE id = :id"),
        {"id": calc_id},
    )
    calc = result.fetchone()
    if not calc:
        return "# Error\n\nCalculation not found.\n"

    title, formula_id, domain, inputs_json, outputs_json, exec_time = calc
    inputs = json.loads(inputs_json) if inputs_json else {}
    outputs = json.loads(outputs_json) if outputs_json else {}

    # Fetch steps
    steps_result = await db.execute(
        text("""
            SELECT step_order, step_type, description, latex_expression
            FROM calculation_steps WHERE calculation_id = :id ORDER BY step_order
        """),
        {"id": calc_id},
    )
    steps = steps_result.fetchall()

    # Build Markdown
    md = f"# Calculation Report: {title}\n\n"
    md += f"**Formula:** `{formula_id}`  \n"
    md += f"**Domain:** {domain}  \n"
    md += f"**Execution Time:** {exec_time:.2f} ms  \n"
    md += f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}  \n\n"

    md += "---\n\n## Input Parameters\n\n"
    md += "| Parameter | Value |\n|---|---|\n"
    for k, v in inputs.items():
        md += f"| {k} | {v} |\n"

    md += "\n## Calculation Steps\n\n"
    for step in steps:
        order, stype, desc, latex_expr = step
        md += f"### Step {order}: {desc}\n\n"
        md += f"**Type:** {stype}  \n"
        md += f"$$\n{latex_expr}\n$$\n\n"

    md += "## Results\n\n"
    md += "| Output | Value |\n|---|---|\n"
    for k, v in outputs.items():
        md += f"| {k} | {v} |\n"

    md += "\n---\n\n*Generated by Troy Engineering Copilot*\n"
    return md


async def _generate_project_summary(project_id: str, db: AsyncSession) -> str:
    """Generate a project summary report."""
    # Fetch project
    result = await db.execute(
        text("SELECT name, description, domain, status, created_at FROM projects WHERE id = :id"),
        {"id": project_id},
    )
    project = result.fetchone()
    if not project:
        return "# Error\n\nProject not found.\n"

    name, desc, domain, status, created = project

    # Count calculations
    calc_result = await db.execute(
        text("SELECT COUNT(*) FROM calculations WHERE project_id = :id"),
        {"id": project_id},
    )
    calc_count = calc_result.scalar()

    # Fetch memory entries
    mem_result = await db.execute(
        text("SELECT entry_type, content FROM memory_entries WHERE project_id = :id ORDER BY created_at"),
        {"id": project_id},
    )
    memories = mem_result.fetchall()

    md = f"# Project Summary: {name}\n\n"
    md += f"**Domain:** {domain}  \n"
    md += f"**Status:** {status}  \n"
    md += f"**Created:** {created}  \n"
    md += f"**Total Calculations:** {calc_count}  \n\n"

    if desc:
        md += f"## Description\n\n{desc}\n\n"

    if memories:
        md += "## Engineering Memory\n\n"
        for mem_type, content in memories:
            md += f"- **[{mem_type.upper()}]** {content}\n"

    md += "\n---\n\n*Generated by Troy Engineering Copilot*\n"
    return md
