import json
from typing import Dict, Any
from datetime import datetime

class AuditReportGenerator:
    @staticmethod
    def generate_markdown(report_data: Dict[str, Any]) -> str:
        lines = [
            "# Engineering Validation & Audit Report",
            f"**Generated:** {datetime.utcnow().isoformat()}",
            f"**Project ID:** {report_data.get('project_id')}",
            "---",
            "## 1. Approval Status",
            f"**Decision:** {report_data.get('approval_status')}",
            f"**Reasoning:** {report_data.get('engineering_reasoning')}",
            "---",
            "## 2. Risk Assessment",
            f"**Overall Risk:** {report_data.get('overall_risk')}",
            "### Identified Risks:"
        ]
        for risk in report_data.get('risk_matrix', []):
            lines.append(f"- **[{risk['severity']}]** {risk['description']}")
            lines.append(f"  - *Fix:* {risk['recommended_fix']}")
        lines.append("---\n*This report was automatically generated by the Day 7 Validation Engine.*")
        return "\n".join(lines)

    @staticmethod
    def generate_json(report_data: Dict[str, Any]) -> str:
        return json.dumps(report_data, indent=2, default=str)
